"""initial migration

Revision ID: 3632d0298668
Revises: 
Create Date: 2021-09-04 09:51:52.589245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3632d0298668'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cd_todos',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('c_text', sa.String(length=50), nullable=True),
    sa.Column('b_complete', sa.Boolean(), nullable=True),
    sa.Column('f_user', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cd_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('c_name', sa.String(length=50), nullable=True),
    sa.Column('c_password', sa.String(length=100), nullable=True),
    sa.Column('b_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cd_users')
    op.drop_table('cd_todos')
    # ### end Alembic commands ###
